import '../../app/modules/calendar/models/activity.dart';
import '../../app/modules/calendar/models/day_schedule.dart';

class DummyBackend {
  static List<DaySchedule> fetchWeek(int weekIndex) {
    switch (weekIndex) {
      case 0:
        return _week0;
      case 1:
        return _week1;
      case -1:
        return _weekMinus1;
      default:
        return _week0;
    }
  }

  static const _week0 = [
    DaySchedule(
      dayName: 'Sun',
      dayNumber: 1,
      monthLabel: 'Feb',
      weather: WeatherType.snow,
      temperature: -2,
      workoutType: WorkoutType.longRide,
      workoutLabel: 'Long Ride',
      workoutDuration: '1h',
      activity: Activity(
        month: 'Feb',
        day: 1,
        title: 'Long Ride',
        subtitle: 'Cycling • 1h • Hard',
        time: 'Today at 6:00',
        isSunny: false,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Feb',
          day: 1,
          title: 'Morning Warm-Up',
          subtitle: 'Stretching • 10m • Easy',
          time: '5:45 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 1,
          title: 'Long Ride',
          subtitle: 'Cycling • 1h • Hard',
          time: '6:00 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 1,
          title: 'Cool Down',
          subtitle: 'Walking • 15m • Easy',
          time: '7:10 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Mon',
      dayNumber: 2,
      monthLabel: 'Feb',
      weather: WeatherType.cloud,
      temperature: 12,
      workoutType: WorkoutType.easyRide,
      workoutLabel: 'Easy Ride',
      workoutDuration: '1h',
      activity: Activity(
        month: 'Feb',
        day: 2,
        title: 'Long Ride',
        subtitle: 'Running • 45m • Moderate',
        time: 'Today at 7:30',
        isSunny: true,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Feb',
          day: 2,
          title: 'Morning Run',
          subtitle: 'Running • 45m • Moderate',
          time: '7:30 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 2,
          title: 'Core Workout',
          subtitle: 'Strength • 20m • Moderate',
          time: '8:30 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 2,
          title: 'Yoga Flow',
          subtitle: 'Flexibility • 30m • Easy',
          time: '9:00 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Tue',
      dayNumber: 3,
      monthLabel: 'Feb',
      weather: WeatherType.storm,
      temperature: -2,
      workoutType: WorkoutType.restDay,
      workoutLabel: 'Strength Training',
      activity: Activity(
        month: 'Feb',
        day: 3,
        title: 'Today Strength Training Workout',
        subtitle: 'Strength • 45m • Intense',
        time: 'Today at 8:00',
        isSunny: false,
        cardType: ActivityCardType.strengthTraining,
        cardDescription: '',
        cardIconEmoji: '💪',
      ),
      activities: [
        Activity(
          month: 'Feb',
          day: 3,
          title: 'Today Strength Training Workout',
          subtitle: 'Strength • 45m • Intense',
          time: '8:00 AM',
          isSunny: false,
          cardType: ActivityCardType.strengthTraining,
          cardDescription: '',
          cardIconEmoji: '💪',
        ),
        Activity(
          month: 'Feb',
          day: 3,
          title: 'Foam Rolling',
          subtitle: 'Recovery • 15m • Easy',
          time: '9:00 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Wed',
      dayNumber: 4,
      monthLabel: 'Feb',
      weather: WeatherType.sun,
      temperature: -2,
      workoutType: WorkoutType.tempoRide,
      workoutLabel: 'Tempo Ride',
      workoutDuration: '1h',
      activity: Activity(
        month: 'Feb',
        day: 4,
        title: 'Tempo Ride',
        subtitle: 'Cycling • 1h • Moderate',
        time: 'Today at 7:00',
        isSunny: true,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Feb',
          day: 4,
          title: 'Tempo Ride',
          subtitle: 'Cycling • 1h • Moderate',
          time: '7:00 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 4,
          title: 'Hill Intervals',
          subtitle: 'Cycling • 20m • Hard',
          time: '8:10 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 4,
          title: 'Protein Shake & Rest',
          subtitle: 'Recovery • 30m',
          time: '8:40 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Thu',
      dayNumber: 5,
      monthLabel: 'Feb',
      weather: WeatherType.storm,
      temperature: -2,
      workoutType: WorkoutType.restDay,
      activities: [],
    ),
    DaySchedule(
      dayName: 'Fri',
      dayNumber: 6,
      monthLabel: 'Feb',
      weather: WeatherType.sun,
      temperature: -2,
      workoutType: WorkoutType.tempoRide,
      workoutLabel: 'Tempo Ride',
      workoutDuration: '1h',
      activity: Activity(
        month: 'Feb',
        day: 6,
        title: 'Tempo Ride',
        subtitle: 'Cycling • 1h • Moderate',
        time: 'Today at 7:00',
        isSunny: true,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Feb',
          day: 6,
          title: 'Tempo Ride',
          subtitle: 'Cycling • 1h • Moderate',
          time: '7:00 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 6,
          title: 'Sprint Intervals',
          subtitle: 'Cycling • 15m • Very Hard',
          time: '8:05 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 6,
          title: 'Stretching',
          subtitle: 'Flexibility • 10m • Easy',
          time: '8:25 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
  ];

  static const _week1 = [
    DaySchedule(
      dayName: 'Sun',
      dayNumber: 8,
      monthLabel: 'Feb',
      weather: WeatherType.sun,
      temperature: 3,
      workoutType: WorkoutType.longRide,
      workoutLabel: 'Long Ride',
      workoutDuration: '2h',
      activity: Activity(
        month: 'Feb',
        day: 8,
        title: 'Long Ride',
        subtitle: 'Cycling • 2h • Hard',
        time: 'Today at 7:00',
        isSunny: true,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Feb',
          day: 8,
          title: 'Long Ride',
          subtitle: 'Cycling • 2h • Hard',
          time: '7:00 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 8,
          title: 'Recovery Stretch',
          subtitle: 'Flexibility • 20m • Easy',
          time: '9:10 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Mon',
      dayNumber: 9,
      monthLabel: 'Feb',
      weather: WeatherType.cloud,
      temperature: 5,
      workoutType: WorkoutType.easyRide,
      workoutLabel: 'Easy Ride',
      workoutDuration: '45m',
      activity: Activity(
        month: 'Feb',
        day: 9,
        title: 'Easy Ride',
        subtitle: 'Cycling • 45m • Easy',
        time: 'Today at 8:00',
        isSunny: false,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Feb',
          day: 9,
          title: 'Easy Ride',
          subtitle: 'Cycling • 45m • Easy',
          time: '8:00 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 9,
          title: 'Light Jog',
          subtitle: 'Running • 20m • Easy',
          time: '8:50 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Tue',
      dayNumber: 10,
      monthLabel: 'Feb',
      weather: WeatherType.storm,
      temperature: -1,
      workoutType: WorkoutType.restDay,
      workoutLabel: 'Strength Training',
      activity: Activity(
        month: 'Feb',
        day: 10,
        title: 'Today Strength Training Workout',
        subtitle: 'Strength • 30m • Intense',
        time: 'Today at 9:00',
        isSunny: false,
        cardType: ActivityCardType.strengthTraining,
        cardDescription:
            'Build your core and increase muscle endurance with this session.',
        cardIconEmoji: '💪',
      ),
      activities: [
        Activity(
          month: 'Feb',
          day: 10,
          title: 'Today Strength Training Workout',
          subtitle: 'Strength • 30m • Intense',
          time: '9:00 AM',
          isSunny: false,
          cardType: ActivityCardType.strengthTraining,
          cardDescription:
              'Build your core and increase muscle endurance with this session.',
          cardIconEmoji: '💪',
        ),
        Activity(
          month: 'Feb',
          day: 10,
          title: 'Plank Challenge',
          subtitle: 'Core • 10m • Hard',
          time: '9:35 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 10,
          title: 'Cool Down Walk',
          subtitle: 'Walking • 15m • Easy',
          time: '9:50 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Wed',
      dayNumber: 11,
      monthLabel: 'Feb',
      weather: WeatherType.snow,
      temperature: -4,
      workoutType: WorkoutType.restDay,
      activities: [],
    ),
    DaySchedule(
      dayName: 'Thu',
      dayNumber: 12,
      monthLabel: 'Feb',
      weather: WeatherType.sun,
      temperature: 2,
      workoutType: WorkoutType.tempoRide,
      workoutLabel: 'Tempo Ride',
      workoutDuration: '1h',
      activity: Activity(
        month: 'Feb',
        day: 12,
        title: 'Tempo Ride',
        subtitle: 'Cycling • 1h • Hard',
        time: 'Today at 6:30',
        isSunny: true,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Feb',
          day: 12,
          title: 'Tempo Ride',
          subtitle: 'Cycling • 1h • Hard',
          time: '6:30 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 12,
          title: 'Cadence Drills',
          subtitle: 'Cycling • 15m • Moderate',
          time: '7:35 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Fri',
      dayNumber: 13,
      monthLabel: 'Feb',
      weather: WeatherType.cloud,
      temperature: 1,
      workoutType: WorkoutType.easyRide,
      workoutLabel: 'Easy Ride',
      workoutDuration: '30m',
      activity: Activity(
        month: 'Feb',
        day: 13,
        title: 'Easy Ride',
        subtitle: 'Cycling • 30m • Easy',
        time: 'Today at 8:30',
        isSunny: false,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Feb',
          day: 13,
          title: 'Easy Ride',
          subtitle: 'Cycling • 30m • Easy',
          time: '8:30 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Feb',
          day: 13,
          title: 'Hip Flexor Stretch',
          subtitle: 'Flexibility • 10m • Easy',
          time: '9:05 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
  ];

  static const _weekMinus1 = [
    DaySchedule(
      dayName: 'Sun',
      dayNumber: 25,
      monthLabel: 'Jan',
      weather: WeatherType.snow,
      temperature: -5,
      workoutType: WorkoutType.restDay,
      activities: [],
    ),
    DaySchedule(
      dayName: 'Mon',
      dayNumber: 26,
      monthLabel: 'Jan',
      weather: WeatherType.cloud,
      temperature: -3,
      workoutType: WorkoutType.easyRide,
      workoutLabel: 'Easy Ride',
      workoutDuration: '1h',
      activity: Activity(
        month: 'Jan',
        day: 26,
        title: 'Easy Ride',
        subtitle: 'Cycling • 1h • Easy',
        time: 'Today at 8:00',
        isSunny: false,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Jan',
          day: 26,
          title: 'Easy Ride',
          subtitle: 'Cycling • 1h • Easy',
          time: '8:00 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Jan',
          day: 26,
          title: 'Balance Drills',
          subtitle: 'Cycling • 10m • Easy',
          time: '9:05 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Tue',
      dayNumber: 27,
      monthLabel: 'Jan',
      weather: WeatherType.storm,
      temperature: -6,
      workoutType: WorkoutType.restDay,
      workoutLabel: 'Strength Training',
      activity: Activity(
        month: 'Jan',
        day: 27,
        title: 'Today Strength Training Workout',
        subtitle: 'Strength • 1h • Intense',
        time: 'Today at 7:00',
        isSunny: false,
        cardType: ActivityCardType.strengthTraining,
        cardDescription:
            'Focus on upper body strength with push and pull exercises.',
        cardIconEmoji: '💪',
      ),
      activities: [
        Activity(
          month: 'Jan',
          day: 27,
          title: 'Today Strength Training Workout',
          subtitle: 'Strength • 1h • Intense',
          time: '7:00 AM',
          isSunny: false,
          cardType: ActivityCardType.strengthTraining,
          cardDescription:
              'Focus on upper body strength with push and pull exercises.',
          cardIconEmoji: '💪',
        ),
        Activity(
          month: 'Jan',
          day: 27,
          title: 'Pull-Ups & Dips',
          subtitle: 'Strength • 20m • Hard',
          time: '8:05 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Jan',
          day: 27,
          title: 'Cool Down',
          subtitle: 'Stretching • 15m • Easy',
          time: '8:30 AM',
          isSunny: false,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Wed',
      dayNumber: 28,
      monthLabel: 'Jan',
      weather: WeatherType.sun,
      temperature: -1,
      workoutType: WorkoutType.tempoRide,
      workoutLabel: 'Tempo Ride',
      workoutDuration: '1h',
      activity: Activity(
        month: 'Jan',
        day: 28,
        title: 'Tempo Ride',
        subtitle: 'Cycling • 1h • Hard',
        time: 'Today at 7:00',
        isSunny: true,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Jan',
          day: 28,
          title: 'Tempo Ride',
          subtitle: 'Cycling • 1h • Hard',
          time: '7:00 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Jan',
          day: 28,
          title: 'Breathing Exercises',
          subtitle: 'Recovery • 10m • Easy',
          time: '8:05 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
    DaySchedule(
      dayName: 'Thu',
      dayNumber: 29,
      monthLabel: 'Jan',
      weather: WeatherType.cloud,
      temperature: 0,
      workoutType: WorkoutType.restDay,
      activities: [],
    ),
    DaySchedule(
      dayName: 'Fri',
      dayNumber: 30,
      monthLabel: 'Jan',
      weather: WeatherType.sun,
      temperature: 2,
      workoutType: WorkoutType.longRide,
      workoutLabel: 'Long Ride',
      workoutDuration: '2h',
      activity: Activity(
        month: 'Jan',
        day: 30,
        title: 'Long Ride',
        subtitle: 'Cycling • 2h • Hard',
        time: 'Today at 6:00',
        isSunny: true,
        cardType: ActivityCardType.regular,
      ),
      activities: [
        Activity(
          month: 'Jan',
          day: 30,
          title: 'Long Ride',
          subtitle: 'Cycling • 2h • Hard',
          time: '6:00 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Jan',
          day: 30,
          title: 'Mountain Climb Sim',
          subtitle: 'Cycling • 30m • Very Hard',
          time: '8:10 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
        Activity(
          month: 'Jan',
          day: 30,
          title: 'Post-Ride Stretch',
          subtitle: 'Flexibility • 15m • Easy',
          time: '8:45 AM',
          isSunny: true,
          cardType: ActivityCardType.regular,
        ),
      ],
    ),
  ];
}
