// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfORxGnIS3Flkb2yJlxIv8SBZwjsJM-rU',
    appId: '1:490515839267:web:4465c9b266432d1597b496',
    messagingSenderId: '490515839267',
    projectId: 'dogbuddy-592d8',
    authDomain: 'dogbuddy-592d8.firebaseapp.com',
    storageBucket: 'dogbuddy-592d8.firebasestorage.app',
    measurementId: 'G-03RQM1EFRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOCa4WRWhmPZVmPpUqZ8pwayh-e3xMBy4',
    appId: '1:490515839267:android:79986eb9738fec8b97b496',
    messagingSenderId: '490515839267',
    projectId: 'dogbuddy-592d8',
    storageBucket: 'dogbuddy-592d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6fWwiITP7pSGXBLt4yVWjt2Z7SehgPKk',
    appId: '1:490515839267:ios:f81c2b02f8cd1e3197b496',
    messagingSenderId: '490515839267',
    projectId: 'dogbuddy-592d8',
    storageBucket: 'dogbuddy-592d8.firebasestorage.app',
    iosBundleId: 'com.dog.dog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6fWwiITP7pSGXBLt4yVWjt2Z7SehgPKk',
    appId: '1:490515839267:ios:f81c2b02f8cd1e3197b496',
    messagingSenderId: '490515839267',
    projectId: 'dogbuddy-592d8',
    storageBucket: 'dogbuddy-592d8.firebasestorage.app',
    iosBundleId: 'com.dog.dog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfORxGnIS3Flkb2yJlxIv8SBZwjsJM-rU',
    appId: '1:490515839267:web:0887a5d7c68bdc3297b496',
    messagingSenderId: '490515839267',
    projectId: 'dogbuddy-592d8',
    authDomain: 'dogbuddy-592d8.firebaseapp.com',
    storageBucket: 'dogbuddy-592d8.firebasestorage.app',
    measurementId: 'G-08YRL893YC',
  );
}
